    version: '3.8'

    services:
      frontend:
        environment:
          # 运行时环境变量（虽然构建时已嵌入，但保留可能有助于调试或某些特定场景）
          - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        build:
          context: ./frontend
          dockerfile: Dockerfile
          args: # 在这里传递构建参数
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL} # 从运行 docker-compose 的环境或 .env 文件获取
        ports:
          - "3060:3000"
        restart: always
        networks:
          - app_network

      backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        environment:
          - OPENAI_API_KEY=${OPENAI_API_KEY}
          - OPENAI_API_BASE=${OPENAI_API_BASE}
          - PLAN_MODEL=${PLAN_MODEL}
          - PLOT_MODEL=${PLOT_MODEL}
          - IMAGE_TO_TEXT_MODEL=${IMAGE_TO_TEXT_MODEL}
          - DATA_ANALYSIS_REPORT_MODEL=${DATA_ANALYSIS_REPORT_MODEL}
        ports:
          - "8060:8000"
        # volumes: # 生产环境通常不挂载代码卷，而是构建到镜像中
        restart: always
        networks:
          - app_network

    networks:
      app_network:
        driver: bridge
